phrase:
  access_token: 7c7de4ee3517982a37b7378da5d0dbc6dbded0a5713a424945d7c97391c6e4c2
  project_id: 21e22bc911a8e565e165c7d7b476a8b7
  file_format: json

  push:
    sources:
    - file: ./en-US_src.json
      params:
        file_format: json
        locale_id: 41585aa320f939155112867d37f32bf0
        update_translations: true
        update_descriptions: true

  pull:
    targets:
    - file: './i18n/fr-FR.json'
      params:
        file_format: json
        locale_id: bd3fcfd5965a86afe23c4b1448df7982