phrase:
  host: https://api.us.app.phrase.com/v2
  project_id: 21e22bc911a8e565e165c7d7b476a8b7
  push:
    sources:
    - file: ./en-US_src.json
      params:
        locale_id: 41585aa320f939155112867d37f32bf0
        file_format: json
  pull:
    targets:
    - file: ./i18n/<locale_name>.json
      params:
        file_format: simple_json
        include_empty_translations: true
        fallback_locale_id: en-US
