name: Test branch

on:
  pull_request:

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          echo "ref_name: ${{ github.ref_name }}"
          echo "ref: ${{ github.ref }}"
          echo "head_ref: ${{ github.head_ref }}"
          echo "base_ref: ${{ github.base_ref }}"
