name: Test branch

on:
  pull_request:

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          CI=true yarn test --json --outputFile test-results.json

      - name: Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            test-results.json
