name: Test CI

on:
  push:
    branches:
      - gha/status-check
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      VAR_REPOSITORY: ${{ secrets.TEST_SECRETS }}
    steps:
      - name: Checkout argo-apps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.VAR_REPOSITORY }}

      - run: |
          echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> './output/text.txt'

      - name: Upload
        uses: actions/upload-artifact@v3
        if: ${{ !cancelled() && steps.result.conclusion == 'failure' }}
        with:
          name: artifact
          path: output
          retention-days: 1

      - name: Build URL
        if: ${{ !cancelled() }}
        env:
          BRANCH_NAME:  ${{ github.head_ref || github.ref_name }}
          BUILD_NUMBER: ${{ github.run_id }}
          BUILD_URL: ${{ format('{0}/{1}/actions/runs/{2}', github.server_url, github.repository, github.run_id) }}
        uses: actions/github-script@v7
        with:
          script: |
            console.log('${{ github.repository }}')
            console.log('${{ env.BRANCH_NAME}}:${{ env.BUILD_URL }}')

  result:
    name: Result
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    steps:
      - name: Check
        run: |
          echo "${{ toJSON(needs.test) }}"
          