name: Test CI

on:
  push:
    branches:
      - gha/status-check
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ secrets.TEST_SECRETS }}
    steps:
      - name: Checkout argo-apps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY }}

      - name: Build URL
        if: ${{ !cancelled() }}
        env:
          BRANCH_NAME:  ${{ github.head_ref || github.ref_name }}
          BUILD_NUMBER: ${{ github.run_id }}
          BUILD_URL: ${{ format('{0}/{1}/actions/runs/{2}', github.server_url, github.repository, github.run_id) }}
        uses: actions/github-script@v7
        with:
          script: |
            core.notice('${{ env.BRANCH_NAME}}:${{ env.BUILD_URL }}')

  result:
    name: Result
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    steps:
      - name: Check
        run: |
          echo "${{ toJSON(needs.test) }}"
          