name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: |
          echo "Test step"
          exit 1
