name: Test CI

on:
  push:
    branches:
      - gha/status-check
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ secrets.TEST_SECRETS }}
    steps:
      - name: Checkout argo-apps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY }}

      - name: Set error
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Error')

  result:
    name: Result
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    steps:
      - name: Check
        run: |
          echo "${{ toJSON(needs.test) }}"
          