name: Test CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:


      - name: Checkout repository
        uses: actions/checkout@v3

  result:
    name: Result
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Foo
        run: |
          npm --version