name: Test CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set error
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Error')

  result:
    name: Result
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Check
        run: |
          echo "{{ fromJSON(needs.test) }}"
          