name: Test CI

on:
  push:
    branches:
      - gha/status-check
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  build:
    name: Build
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build success"

  result:
    name: Result
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ !cancelled() }}
    steps:
      - name: Check
        run: |
          echo "${{ needs.*.result }}"
          