name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: |
          echo "Test step"
          exit 1

  result:
    name: Result
    runs-on: ubuntu-latest
    steps:
      - name: Foo
        run: |
          npm --version